apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://download.elastic.co/downloads/eck/2.13.0/crds.yaml
  - https://download.elastic.co/downloads/eck/2.13.0/operator.yaml